/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailclient;
import java.awt.Color;
import java.awt.Toolkit;

import java.io.File;
import java.io.IOException;

import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;


import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import javax.mail.MessagingException;
import javax.mail.internet.AddressException;



import javax.mail.Multipart;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMultipart;
import javax.swing.*;
import sun.misc.BASE64Encoder;




/**
 *
 * @author Huynh-The-Vinh
 */
public class sendMail extends javax.swing.JFrame {

    String to, subject, content, from, smtpHost, smtpPort,password;
    Account account;
    Message msg;
    int soNguoinhan=1;
    int soFile=0;
    File[] attachFiles = null;
    DefaultListModel listModel = new DefaultListModel();
    /**
     * Creates new form NewJFrame
     */
    public sendMail() {
        initComponents();
        setIcon();
        listModel.removeAllElements();
        listAttach.setModel(listModel);
    }

    public sendMail(String fromEmail,String fromPassword, String toEmail, String Subject, String content,String host,String port )
    {
        from = fromEmail;
        password = fromPassword;
        to = toEmail;
        subject = Subject;
        smtpHost = host;
        smtpPort = port;
        initComponents();
        tbNguoinhan.setText(to);
        tbTieude.setText(subject);
        tbNoidung.setText(content);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSend = new javax.swing.JButton();
        btAttach = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbNguoinhan = new javax.swing.JTextField();
        tbTieude = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNoidung = new javax.swing.JEditorPane();
        btCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listAttach = new javax.swing.JList();
        btDelAttach = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbStt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbEncrypt = new javax.swing.JCheckBox();
        tbKey = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbKeyLength = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gửi Email");
        setPreferredSize(new java.awt.Dimension(800, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mail_send.png"))); // NOI18N
        btSend.setText("Gửi");
        btSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendActionPerformed(evt);
            }
        });

        btAttach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/attachment.png"))); // NOI18N
        btAttach.setText("Đính kèm");
        btAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAttachActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/compose_email.png"))); // NOI18N
        jLabel3.setText("SOẠN EMAIL");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin Mail gửi"));

        jLabel1.setText("Người nhận");

        tbNguoinhan.setToolTipText("Nhập các địa chỉ email muốn gửi, cách nhau bởi dấu \";\"");
        tbNguoinhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNguoinhanMouseClicked(evt);
            }
        });

        jLabel2.setText("Tiêu đề:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel4.setText("(Gửi cho nhiều email được ngăn cách bởi dấu \";\")");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbTieude)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbNguoinhan))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tbNguoinhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbTieude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbNoidung.setBorder(javax.swing.BorderFactory.createTitledBorder("Nội dung"));
        tbNoidung.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(tbNoidung);

        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btCancel.setText("Hủy");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listAttach);

        btDelAttach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btDelAttach.setText("Xóa file");
        btDelAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelAttachActionPerformed(evt);
            }
        });

        jLabel5.setText("Dung lượng tối đa 10mb");

        lbStt.setText("_");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        cbEncrypt.setText("Mã hóa Email");

        tbKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbKeyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbKeyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbKeyKeyTyped(evt);
            }
        });

        jLabel6.setText("Nhập key mã hóa và giải mã Emai (độ dài = 16 kí tự)");

        jLabel7.setText("Số kí tự: ");

        lbKeyLength.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbKey)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEncrypt)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbKeyLength)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbEncrypt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(tbKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbKeyLength))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btSend, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btAttach)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btDelAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbStt, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSend)
                            .addComponent(btCancel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btAttach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                    .addComponent(btDelAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStt)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendActionPerformed
        String sourceEmail = tbNoidung.getText();
        String noidung = sourceEmail;
        String desKey = "ThisIsFoundation";
        if (cbEncrypt.isSelected())
        {
            if (tbKey.getText().length()==16)
            {
            try {
                
                desKey = tbKey.getText();
                
                {
                    
                    noidung = EncryptorDecryptor.encrypt(sourceEmail,desKey);
                }
                
                
            } catch (Exception ex) {
                Logger.getLogger(sendMail.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Lỗi: "+ex,"Lỗi",0);
            }
            }
            else 
            {
                JOptionPane.showMessageDialog(null,"Bạn phải nhập key dùng để mã hõa (độ dài key = 16)", "Lỗi",0);
                return;
            }
        }
        else noidung = tbNoidung.getText();
        if (tbNguoinhan.getText()=="")
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập email người nhận","Lỗi",0);
        else 
        {
        to = tbNguoinhan.getText();
        subject = tbTieude.getText();
        try {
            lbStt.setForeground(Color.ORANGE);
            lbStt.setText("Đang tiến hành gửi mail. Xin vui lòng đợi...");
            sendHtmlEmail(smtpHost, smtpPort, from, password, to, subject, noidung);
            lbStt.setForeground(Color.BLUE);
            lbStt.setText("Gửi mail thành công!");
            JOptionPane.showMessageDialog(null,"Gửi email tới: "+to+" thành công!","Thông báo",1);
            
        } catch (MessagingException ex) {
            Logger.getLogger(sendMail.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Lỗi gửi mail! "+ex,"Lỗi!",0);
        }
        }
    }//GEN-LAST:event_btSendActionPerformed

    private void btAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAttachActionPerformed
        // TODO add your handling code here: ĐÍnh kèm file
        soFile = 0;
        attachFiles = null;
        // Mo file can gui
        JFileChooser fc = new JFileChooser();
        int returnVal;
        fc.setMultiSelectionEnabled(true);
        returnVal = fc.showOpenDialog(this);
   
    if(returnVal == JFileChooser.APPROVE_OPTION) {
       attachFiles = fc.getSelectedFiles();
       
       for (File file:attachFiles)
       {
           if ((file.getName()!=null)&&(file.length()<=10000000))
           {
               listModel.addElement(file.getName());
               listAttach.setModel(listModel);
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Đính kèm không thành công!","Thông báo",0);  
               return;
               
           }
       }
       
          JOptionPane.showMessageDialog(null,"Đính kèm thành công!","Thông báo",1);  
    }
    //Gui thu kem voi noi dung
    
    
    
    
    }//GEN-LAST:event_btAttachActionPerformed

    private void tbNguoinhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNguoinhanMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbNguoinhanMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //tbKey.setEnabled(false);
       
       //smtpHost = account.getSmtpHost();
       //smtpPort = account.getSmtpPort();
       //from = account.getEmail();
       //password = account.getPassword();
        //System.out.println(smtpHost);
       
        
    }//GEN-LAST:event_formWindowActivated

    private void btDelAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelAttachActionPerformed
        // TODO add your handling code here:
        listModel.removeAllElements();
        attachFiles = null;
    }//GEN-LAST:event_btDelAttachActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void tbKeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKeyKeyTyped
        // TODO add your handling code here:
         
    }//GEN-LAST:event_tbKeyKeyTyped

    private void tbKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKeyKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbKeyKeyPressed

    private void tbKeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKeyKeyReleased
        // TODO add your handling code here:
        int keyLength = 0;
        if (tbKey.getText().isEmpty()) 
            keyLength = 0;
        else keyLength = tbKey.getText().length();
        lbKeyLength.setText(Integer.toString(keyLength));
    }//GEN-LAST:event_tbKeyKeyReleased

    public void sendHtmlEmail(String host, String port,
			final String userName, final String password, String toAddress,
			String subject, String message) throws AddressException,
			MessagingException {

		// cài đặt thuộc tính gửi mail
		Properties properties = new Properties();
		properties.put("mail.smtp.host", host);
		properties.put("mail.smtp.port", port);
		properties.put("mail.smtp.auth", "true");
		properties.put("mail.smtp.starttls.enable", "true");

		// tạo xác thực
		Authenticator auth = new Authenticator() {
			public PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(userName, password);
			}
		};

		Session session = Session.getInstance(properties, auth);

		// Tạo mail mới
		Message msg = new MimeMessage(session);

		msg.setFrom(new InternetAddress(userName));
        
                //Thiet lap gui mail cho nhieu nguoi
		//InternetAddress[] toAddresses = { new InternetAddress(toAddress) };
                toAddress.trim();
                String[] addresses =  toAddress.split(";");
                soNguoinhan = 0;
                for (int i=0;i<addresses.length;i++)
                {
                    if (addresses[i]!="")
                        soNguoinhan++;
                }
                InternetAddress[] toAddresses = new InternetAddress[soNguoinhan];
                for (int i=0;i<soNguoinhan;i++)
                {
                    toAddresses[i] = new InternetAddress(addresses[i]);
                }
		msg.setRecipients(Message.RecipientType.TO, toAddresses);
		msg.setSubject(subject);
		msg.setSentDate(new Date());
                
		

                //gui file dinh kem neu co
                if ((attachFiles != null) && (attachFiles.length > 0))
                {
                    // tạo part chứa nội dung
                    MimeBodyPart messageBodyPart = new MimeBodyPart();
                    messageBodyPart.setContent(message, "text/html; charset=UTF-8");
                    
                    //tạo multipart 
                     Multipart multipart = new MimeMultipart();
                    multipart.addBodyPart(messageBodyPart); // part chứa nội dung mail
                    
                    //tạo part chứa file đính kèm
                    for (File file:attachFiles)
                    {
                        try {
                        
                            MimeBodyPart attachPart = new MimeBodyPart();
                        
                            attachPart.attachFile(file);
                            multipart.addBodyPart(attachPart);
                        } catch (IOException ex) {
                            JOptionPane.showMessageDialog(null, "Lỗi đính kèm file!"+ex, "Lỗi", 0);
                        }
                        
                        
                    }
                  msg.setContent(multipart);
                  
                }
                else {
                // set plain text message
		msg.setContent(message, "text/html; charset=UTF-8"); 
                }
		// sends the e-mail
		Transport.send(msg);

	}
    /**
     *
     * @param args
     */
    public static void main(String args[ ]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Lỗi! "+ex,"Lỗi",0);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new sendMail().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAttach;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDelAttach;
    private javax.swing.JButton btSend;
    private javax.swing.JCheckBox cbEncrypt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbKeyLength;
    private javax.swing.JLabel lbStt;
    private javax.swing.JList listAttach;
    private javax.swing.JTextField tbKey;
    private javax.swing.JTextField tbNguoinhan;
    private javax.swing.JEditorPane tbNoidung;
    private javax.swing.JTextField tbTieude;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon/mailm.png")));
    }

    
}
