Delivered-To: demolaptrinhmang@gmail.com
Received: by 10.76.41.42 with SMTP id c10csp211552oal;
        Fri, 29 May 2015 02:42:50 -0700 (PDT)
X-Received: by 10.70.102.132 with SMTP id fo4mr13564060pdb.31.1432892569970;
        Fri, 29 May 2015 02:42:49 -0700 (PDT)
Return-Path: <steamsell94@gmail.com>
Received: from mail-pa0-x236.google.com (mail-pa0-x236.google.com. [2607:f8b0:400e:c03::236])
        by mx.google.com with ESMTPS id gi11si7602283pbd.206.2015.05.29.02.42.49
        for <demoLaptrinhmang@gmail.com>
        (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 29 May 2015 02:42:49 -0700 (PDT)
Received-SPF: pass (google.com: domain of steamsell94@gmail.com designates 2607:f8b0:400e:c03::236 as permitted sender) client-ip=2607:f8b0:400e:c03::236;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of steamsell94@gmail.com designates 2607:f8b0:400e:c03::236 as permitted sender) smtp.mail=steamsell94@gmail.com;
       dkim=pass header.i=@gmail.com;
       dmarc=pass (p=NONE dis=NONE) header.from=gmail.com
Received: by mail-pa0-x236.google.com with SMTP id bw4so51608548pad.0
        for <demoLaptrinhmang@gmail.com>; Fri, 29 May 2015 02:42:49 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=date:from:to:message-id:subject:mime-version:content-type
         :content-transfer-encoding;
        bh=j6g3kToG7XlFOCg0HhZdkLemfmT8+mb7VvqyiVSejvI=;
        b=t1i7bWpLoiv7wg9cx2q52cnFMtFYvCnzlF5x/cZRU2wB9KTEAzZtqHzA5H4pdVCK3t
         pVKDunh9dLako5fonUmjmI5TugsSuif29TtL8jjdnzZZqY95rBpVR68Ryg4hrR9cDXto
         zFQfiWOBk0wCgi0+TwW8YwfiCybCCmpM8Zb8oL9i8978HKu2QsjS2A+sUoxtreHWrqvo
         n4iKzp7TChjqfyEagTpY8PDWJHFJjMQM9bOxPzBxYwQM5iGqYLOVbBNR69U6Tdpe+gPE
         sYSs1u3TI8aL9PL9Z/SWxxKmdS0iEFlX2ODX/YplTKV1R2W6Y9qaQ4ycvBM0H9Sginzi
         twog==
X-Received: by 10.66.141.132 with SMTP id ro4mr13765388pab.50.1432892569599;
        Fri, 29 May 2015 02:42:49 -0700 (PDT)
Return-Path: <steamsell94@gmail.com>
Received: from HH-PC ([1.52.234.39])
        by mx.google.com with ESMTPSA id mi1sm5012930pab.0.2015.05.29.02.42.47
        for <demoLaptrinhmang@gmail.com>
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Fri, 29 May 2015 02:42:48 -0700 (PDT)
Date: Fri, 29 May 2015 16:42:41 +0700 (ICT)
From: steamsell94@gmail.com
To: demoLaptrinhmang@gmail.com
Message-ID: <1342035447.3.1432892561748.JavaMail.ThanhHung@HH-PC>
Subject: =?UTF-8?Q?Forward:_=C4=90=C4=83ng_nh=E1=BA=ADp_=C4=91=C3=A1?=
 =?UTF-8?Q?ng_ng=E1=BB=9D_=C4=91=C3=A3_b=E1=BB=8B_ng=C4=83n_ch=E1=BA=B7n?=
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<html lang="vi">
  <head>
    
  </head>
  <body style="margin-top: 0; margin-right: 0; margin-bottom: 0; margin-left: 0; padding-top: 0; padding-right: 0; padding-bottom: 0; padding-left: 0">
    <table bgcolor="#f1f1f1" width="100%" height="60" align="center" border="0" cellspacing="0" cellpadding="0">
      <tr align="center">
        <td valign="top">
          <table bgcolor="#f1f1f1" height="60" border="0" cellspacing="0" cellpadding="0">
            <tr valign="middle" height="40">
              <td width="9">
                
              </td>
              <td width="217" valign="middle">
                <img src="cid:google" border="0" alt="Google Accounts" height="40" style="display: block">
                
              </td>
              <td width="327" align="right">
                Sell Steam
              </td>
              <td width="10">
                
              </td>
              <td>
                <img src="cid:profilephoto" width="27" height="27">
                
              </td>
              <td width="10">
                
              </td>
            </tr>
          </table>
          <table border="1" bordercolor="#e5e5e5" cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="left">
            <tr>
              <td height="15" style="border-top-color: border-color; border-top-style: none; border-top-width: medium; border-bottom-color: border-color; border-bottom-style: none; border-bottom-width: medium; border-left-color: border-color; border-left-style: none; border-left-width: medium; border-right-color: border-color; border-right-style: none; border-right-width: medium">
                
              </td>
            </tr>
            <tr>
              <td width="15" style="border-top-color: border-color; border-top-style: none; border-top-width: medium; border-bottom-color: border-color; border-bottom-style: none; border-bottom-width: medium; border-left-color: border-color; border-left-style: none; border-left-width: medium; border-right-color: border-color; border-right-style: none; border-right-width: medium">
                
              </td>
              <td width="568" valign="top" style="border-top-color: border-color; border-top-style: none; border-top-width: medium; border-bottom-color: border-color; border-bottom-style: none; border-bottom-width: medium; border-left-color: border-color; border-left-style: none; border-left-width: medium; border-right-color: border-color; border-right-style: none; border-right-width: medium; line-height: 18px">
                Xin ch&#224;o Sell,<br><br>G&#226;&#768;n &#273;&#226;y co&#769; ng&#432;&#417;&#768;i na&#768;o &#273;o&#769; &#273;a&#771; 
                s&#432;&#777; du&#803;ng m&#226;&#803;t kh&#226;&#777;u cu&#777;a ba&#803;n &#273;&#234;&#777; ti&#768;m ca&#769;ch &#273;&#259;ng nh&#226;&#803;p ta&#768;i 
                khoa&#777;n Google steamsell94@gmail.com cu&#777;a ba&#803;n. Ng&#432;&#417;&#768;i na&#768;y 
                &#273;ang s&#432;&#777; du&#803;ng m&#244;&#803;t &#432;&#769;ng du&#803;ng, ch&#259;&#777;ng ha&#803;n nh&#432; &#432;&#769;ng du&#803;ng 
                email kha&#769;ch ho&#259;&#803;c thi&#234;&#769;t bi&#803; di &#273;&#244;&#803;ng.<br><br>Ch&#250;ng 
                t&#244;i &#273;&#227; ng&#259;n ch&#7863;n n&#7895; l&#7921;c &#273;&#259;ng nh&#7853;p trong tr&#432;&#7901;ng h&#7907;p &#273;&#226;y l&#224; m&#7897;t 
                k&#7867; x&#226;m nh&#7853;p c&#7889; g&#7855;ng truy c&#7853;p t&#224;i kho&#7843;n c&#7911;a b&#7841;n. Vui l&#242;ng xem 
                l&#7841;i th&#244;ng tin chi ti&#7871;t v&#7873; n&#7895; l&#7921;c &#273;&#259;ng nh&#7853;p:<br><br>

                <table align="left" border="0" cellspacing="0" cellpadding="0" width="100%">
                  <tr valign="middle">
                    <td width="13">
                      
                    </td>
                    <td>
                      9:47 SA GMT+7 Ch&#7911; Nh&#7853;t, 26 th&#225;ng 4<br>&#272;&#7883;a 
                      ch&#7881; IP: 14.165.177.33<br>V&#7883; tr&#237;: tp. Tuy H&#242;a, Ph&#250; 
                      Y&#234;n, Vi&#7879;t Nam
                    </td>
                  </tr>
                  <tr>
                    <td height="15" style="border-top-color: border-color; border-top-style: none; border-top-width: medium; border-bottom-color: border-color; border-bottom-style: none; border-bottom-width: medium; border-left-color: border-color; border-left-style: none; border-left-width: medium; border-right-color: border-color; border-right-style: none; border-right-width: medium">
                      
                    </td>
                  </tr>
                </table>
                <br>
                <br>
                N&#7871;u b&#7841;n kh&#244;ng nh&#7853;n ra ho&#7841;t &#273;&#7897;ng &#273;&#259;ng nh&#7853;p n&#224;y, ai &#273;&#243; kh&#225;c c&#243; 
                th&#7875; &#273;ang c&#7889; g&#7855;ng truy c&#7853;p t&#224;i kho&#7843;n c&#7911;a b&#7841;n. B&#7841;n n&#234;n &#273;&#259;ng nh&#7853;p 
                v&#224;o t&#224;i kho&#7843;n c&#7911;a m&#236;nh v&#224; &#273;&#7863;t l&#7841;i m&#7853;t kh&#7849;u ngay l&#7853;p t&#7913;c.<br><br><a href="http://support.google.com/accounts?p=reset_pw" target="_blank" align="center" style="border-top-color: #3079ed; border-right-color: #3079ed; border-bottom-color: #3079ed; border-left-color: #3079ed; background-color: #4d90fe; background-image: linear-gradient(top,#4d90fe,#4787ed); display: inline-block; height: 27px; padding-left: 8px; padding-right: 8px; line-height: 27px; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px"><font size="11px" face="arial, sans-serif" color="white"><b><span>&#272;&#7863;t 
                l&#7841;i m&#7853;t kh&#7849;u </span></b></font></a><br><br>N&#7871;u 
                &#273;&#226;y l&#224; b&#7841;n v&#224; b&#7841;n &#273;ang g&#7863;p s&#7921; c&#7889; khi truy c&#7853;p t&#224;i kho&#7843;n c&#7911;a 
                m&#236;nh, h&#227;y ho&#224;n t&#7845;t c&#225;c b&#432;&#7899;c kh&#7855;c ph&#7909;c s&#7921; c&#7889; &#273;&#432;&#7907;c li&#7879;t k&#234; t&#7841;i <a href="http://support.google.com/mail?p=client_login" target="_blank">http://support.google.com/mail?p=client_login</a><br><br>Tr&#226;n 
                tr&#7885;ng,<br>Nh&#243;m t&#224;i kho&#7843;n Google
              </td>
              <td width="15" style="border-top-color: border-color; border-top-style: none; border-top-width: medium; border-bottom-color: border-color; border-bottom-style: none; border-bottom-width: medium; border-left-color: border-color; border-left-style: none; border-left-width: medium; border-right-color: border-color; border-right-style: none; border-right-width: medium">
                
              </td>
            </tr>
            <tr>
              <td height="15" style="border-top-color: border-color; border-top-style: none; border-top-width: medium; border-bottom-color: border-color; border-bottom-style: none; border-bottom-width: medium; border-left-color: border-color; border-left-style: none; border-left-width: medium; border-right-color: border-color; border-right-style: none; border-right-width: medium">
                
              </td>
            </tr>
            <tr>
              <td width="15" style="border-top-color: border-color; border-top-style: none; border-top-width: medium; border-bottom-color: border-color; border-bottom-style: none; border-bottom-width: medium; border-left-color: border-color; border-left-style: none; border-left-width: medium; border-right-color: border-color; border-right-style: none; border-right-width: medium">
                
              </td>
              <td width="568" style="border-top-color: border-color; border-top-style: none; border-top-width: medium; border-bottom-color: border-color; border-bottom-style: none; border-bottom-width: medium; border-left-color: border-color; border-left-style: none; border-left-width: medium; border-right-color: border-color; border-right-style: none; border-right-width: medium">
                Email n&#224;y kh&#244;ng th&#7875; nh&#7853;n &#273;&#432;&#7907;c th&#432; tr&#7843; l&#7901;i. &#272;&#7875; bi&#7871;t th&#234;m th&#244;ng 
                tin, truy c&#7853;p v&#224;o <a href="https://support.google.com/accounts"><font color="#4D90FE"><span>Trung 
                t&#226;m tr&#7907; gi&#250;p c&#7911;a t&#224;i kho&#7843;n Google</span></font></a>.
              </td>
              <td width="15" style="border-top-color: border-color; border-top-style: none; border-top-width: medium; border-bottom-color: border-color; border-bottom-style: none; border-bottom-width: medium; border-left-color: border-color; border-left-style: none; border-left-width: medium; border-right-color: border-color; border-right-style: none; border-right-width: medium">
                
              </td>
            </tr>
            <tr>
              <td height="15" style="border-top-color: border-color; border-top-style: none; border-top-width: medium; border-bottom-color: border-color; border-bottom-style: none; border-bottom-width: medium; border-left-color: border-color; border-left-style: none; border-left-width: medium; border-right-color: border-color; border-right-style: none; border-right-width: medium">
                
              </td>
            </tr>
          </table>
          <table bgcolor="#f1f1f1" height="80" align="left">
            <tr valign="middle">
              <td>
                B&#7841;n &#273;&#227; nh&#7853;n th&#244;ng b&#225;o d&#7883;ch v&#7909; qua email b&#7855;t bu&#7897;c n&#224;y &#273;&#7875; c&#7853;p 
                nh&#7853;t v&#7873; nh&#7919;ng thay &#273;&#7893;i quan tr&#7885;ng cho s&#7843;n ph&#7849;m ho&#7863;c t&#224;i kho&#7843;n 
                Google c&#7911;a b&#7841;n.<br><br>

                <div>
                  &#169; 2015 Google Inc., 1600 Amphitheatre Parkway, Mountain 
                  View, CA 94043, USA
                </div>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
