Delivered-To: demolaptrinhmang@gmail.com
Received: by 10.107.37.3 with SMTP id l3csp172617iol;
        Wed, 3 Jun 2015 17:57:59 -0700 (PDT)
X-Received: by 10.68.113.194 with SMTP id ja2mr26206194pbb.163.1433379479098;
        Wed, 03 Jun 2015 17:57:59 -0700 (PDT)
Return-Path: <steamsell94@gmail.com>
Received: from mail-pa0-x22e.google.com (mail-pa0-x22e.google.com. [2607:f8b0:400e:c03::22e])
        by mx.google.com with ESMTPS id y3si3242147pbt.81.2015.06.03.17.57.58
        for <demolaptrinhmang@gmail.com>
        (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Wed, 03 Jun 2015 17:57:59 -0700 (PDT)
Received-SPF: pass (google.com: domain of steamsell94@gmail.com designates 2607:f8b0:400e:c03::22e as permitted sender) client-ip=2607:f8b0:400e:c03::22e;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of steamsell94@gmail.com designates 2607:f8b0:400e:c03::22e as permitted sender) smtp.mail=steamsell94@gmail.com;
       dkim=pass header.i=@gmail.com;
       dmarc=pass (p=NONE dis=NONE) header.from=gmail.com
Received: by mail-pa0-x22e.google.com with SMTP id qy3so17623534pab.3
        for <demolaptrinhmang@gmail.com>; Wed, 03 Jun 2015 17:57:58 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=date:from:to:message-id:subject:mime-version:content-type
         :content-transfer-encoding;
        bh=81N5391MOcrazhD377QdC0GkwfHUdxn5tIZYkVJ2D+c=;
        b=NcJFzK5vWSswI30+W2Iil0hfdMXsH3blxmfCo95ZYUPXv2/gf5zYHrC6YtTnOWNDZO
         rVh93bLOtVopcunffPn5MEohHmT+Demg6TOw3pWNeSE/0RSUWcNIqoOJf7PPBapr/Ndd
         khtCpnGo+NR1RDZd9kVzgoLt4GqRCFZG1LIsxFf6NgrmXgDj/5MrBrIlE34IJxtiH+/u
         N92fdlqQU4a2CQMWhtyVQ/YJKQNhYTItRc/CHeVCvW8XoPzz0DqpmDQEjfWmAMg6nfuJ
         7d6TuXgJ7ojsHY/6GcQLEt95VLqwyCypAoKxYYfM7NlPDRJ3eIR1hCFSPESWxIuC9IoA
         ugEg==
X-Received: by 10.66.122.5 with SMTP id lo5mr15254643pab.141.1433379478680;
        Wed, 03 Jun 2015 17:57:58 -0700 (PDT)
Return-Path: <steamsell94@gmail.com>
Received: from HH-PC ([171.254.20.216])
        by mx.google.com with ESMTPSA id oo3sm1962283pac.31.2015.06.03.17.57.56
        for <demolaptrinhmang@gmail.com>
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Wed, 03 Jun 2015 17:57:57 -0700 (PDT)
Date: Thu, 4 Jun 2015 07:57:48 +0700 (ICT)
From: steamsell94@gmail.com
To: demolaptrinhmang@gmail.com
Message-ID: <1175197266.0.1433379468273.JavaMail.ThanhHung@HH-PC>
Subject: =?UTF-8?Q?Rep:_G=E1=BB=ADi_mail_qua_mail_client?=
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<html>
  <head>

  </head>
  <body>
    <p style="margin-top: 0">
      Xin c&#7843;m &#417;n, &#273;&#227; nh&#7853;n &#273;&#432;&#7907;c mail
    </p>
  </body>
</html>
