Return-Path: <demolaptrinhmang@gmail.com>
Received: from HH-PC ([58.186.211.162])
        by mx.google.com with ESMTPSA id zs5sm8281714pac.11.2015.06.13.22.50.21
        for <demoLaptrinhmang@gmail.com>
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Sat, 13 Jun 2015 22:50:22 -0700 (PDT)
From: demolaptrinhmang@gmail.com
X-Google-Original-From: demoLaptrinhmang@gmail.com
Date: Sun, 14 Jun 2015 12:50:17 +0700 (ICT)
To: demoLaptrinhmang@gmail.com
Message-ID: <4686395.0.1434261017372.JavaMail.ThanhHung@HH-PC>
Subject: xin chao cac ban
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

gyRBPFlRV6v59LyBetDsQrrYivdb5NOVjYVTanxv7UPSM82e+K+0x9+vxmlh7Ao/KyfWVurrarNn
tneJYraK/gxMVPWZaEPxZFBX+ihVjmKy9GVBp4dVVmr/vSADH2+fEFgbIdYpBc45xPrZrB603eoN
19Inxyk3lhd09wD3VMJe0Fdkjx5YlFWGMnKZtygNUe92pFxujiLz+df2aKv6pyTmYgPlb9u0TDcY
Rd5LQj7XYmMMGm2c/Xqo2rzHZw9d
