Delivered-To: steamsell94@gmail.com
Received: by 10.152.3.137 with SMTP id c9csp73460lac;
        Sat, 1 Nov 2014 10:44:55 -0700 (PDT)
X-Received: by 10.66.119.175 with SMTP id kv15mr32875923pab.30.1414863894336;
        Sat, 01 Nov 2014 10:44:54 -0700 (PDT)
Return-Path: <noreply@steampowered.com>
Received: from smtp01.steampowered.com (smtp01.steampowered.com. [208.64.202.37])
        by mx.google.com with ESMTPS id ru12si11844900pac.48.2014.11.01.10.44.53
        for <steamsell94@gmail.com>
        (version=TLSv1 cipher=RC4-SHA bits=128/128);
        Sat, 01 Nov 2014 10:44:54 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@steampowered.com designates 208.64.202.37 as permitted sender) client-ip=208.64.202.37;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of noreply@steampowered.com designates 208.64.202.37 as permitted sender) smtp.mail=noreply@steampowered.com;
       dkim=pass header.i=@steampowered.com
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=steampowered.com; s=smtp;
	h=Date:Message-Id:Content-Type:Subject:MIME-Version:Reply-To:From:To; bh=bUTEh5YCApSdekiTZiLIvM3Uknm+5Qj0EIIib6suuZA=;
	b=Rpof7+OYFiQyrBL3M2G8fhIHA4E6jCpV0/0QHtAq7sg6EVfYtuqVAysZfhG1CMsXD3Cv0UOskSTVhnXAi3fXY5Z3HPvdawHhenR5Qv2WKWgwDxG+sIu/FuJSNLsn1RoJiaE6r/9VDvbU4Tyyc7HDQvc604sp27tK0GbbWqB5yBo=;
Received: from [10.3.8.109] (helo=valvesoftware.com)
	by smtp01.steampowered.com with smtp (Exim 4.76)
	(envelope-from <noreply@steampowered.com>)
	id 1Xkcb8-0007ho-BP
	for steamsell94@gmail.com; Sat, 01 Nov 2014 10:36:22 -0700
To: steamsell94@gmail.com
From: Steam Support <noreply@steampowered.com>
Reply-To: <noreply@steampowered.com>
X-Steam-Message-Type: Account Information Confirmation
MIME-Version: 1.0
Subject: Your Steam account: Email address verification
Content-Type: multipart/alternative;
 boundary="------------060908020109090601040503"
Message-Id: <E1Xkcb8-0007ho-BP@smtp01.steampowered.com>
Date: Sat, 01 Nov 2014 10:36:22 -0700

This is a multi-part message in MIME format.
--------------060908020109090601040503
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit


Dear steamsellxx, 


In order to help maintain the security of your Steam account, please verify your email 
address by visiting the following URL: http://steamcommunity.com/actions/validateemail?stoken=150965716_50567929_1674428191 

Your email address will be used to assist you in changing your Steam account credentials 
or regaining access to your Steam account, should you ever need help with those things. 

Thanks for helping us maintain the security of your account.


The Steam Support Team
http://www.steampowered.com 



==============
This notification has been sent to the email address associated with your Steam account. 
For information on Valve's privacy policy, visit http://www.valvesoftware.com/privacy.htm. 
This email message was auto-generated. Please do not respond.

© Valve Corporation. All rights reserved. All trademarks are property of their respective 
owners in the US and other countries.


--------------060908020109090601040503
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<html>
<head>
  <meta content="text/html;charset=UTF-8" http-equiv="Content-Type">
</head>
<body bgcolor="#ffffff" text="#000000" LINK="#517ba4" ALINK="#517ba4" VLINK="#517ba4">


<span style="font-size: 10px; background: #000000; color: #999999; font-family: Trebuchet MS,Verdana,Arial,Helvetica,sans-serif; align: left; lang="x-western">
		<img src="http://storefront.steampowered.com/v/img/email/STEAM_mail.jpg" alt="&nbsp;STEAM&nbsp;" width="430" height="48" border="0"><BR>
</span>
<div style="width: 430px; font-size: 11px; color: #333333; font-family: Trebuchet MS,Verdana,Arial,Helvetica,sans-serif;  lang="x-western">
  <BR>
  Dear steamsellxx, <br>

  <p>In order to help maintain the security of your Steam account, please verify your email address by clicking the following link: <a href="http://steamcommunity.com/actions/validateemail?stoken=150965716_50567929_1674428191">http://steamcommunity.com/actions/validateemail?stoken=150965716_50567929_1674428191</a>. </p>
    <p>Your email address will be used to assist you in changing your Steam account credentials or regaining access to your Steam account, should you ever need help with those things. </p>
    <p>Thanks for helping us maintain the  security of your account.<BR>
<p>The Steam Support Team<br>
    <a href="http://www.steampowered.com">http://www.steampowered.com</a> <br>
<p></p>
<br>
<br>
<span style="color: #333333; font-size: 9px; font-family: Trebuchet MS, Verdana, Arial, Helvetica, sans-serif;"><span style="color: #333333; font-size: 9px; font-family: Trebuchet MS, Verdana, Arial, Helvetica, sans-serif;">This </span></span><span style="color: #333333; font-size: 9px; font-family: Trebuchet MS, Verdana, Arial, Helvetica, sans-serif;">notification has been sent to the email address associated with your Steam account. <br>
  For information on Valve's privacy policy, visit <a href="http://www.valvesoftware.com/privacy.htm">http://www.valvesoftware.com/privacy.htm</a>. <br>
  This email message was auto-generated. Please do not respond.</span><br>
      
    <span style="color: #333333; font-size: 9px; font-family: Trebuchet MS, Verdana, Arial, Helvetica, sans-serif;"></span><span style="color: #333333; font-size: 9px; font-family: Trebuchet MS, Verdana, Arial, Helvetica, sans-serif;">
    </span><span style="color: #333333; font-size: 9px; font-family: Trebuchet MS, Verdana, Arial, Helvetica, sans-serif;">
    <hr color="#666666" align="left" width="420" size="1" noshade>
  <span style="color: #333333; font-size: 9px; font-family: Trebuchet MS, Verdana, Arial, Helvetica, sans-serif;"><span style="color: #333333; font-size: 9px; font-family: Trebuchet MS, Verdana, Arial, Helvetica, sans-serif;"> </span></span></span>
  <table width="420" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td><span style="font-size: 10px; background: #FFFFFF; color: #333333; font-family: Trebuchet MS,Verdana,Arial,Helvetica,sans-serif; align: left; lang="x-western"><img src="http://storefront.steampowered.com/v/img/email/VALVE_mail.gif" alt="VALVE" width="91" height="25"></span></td>
      <td width="320"><span style="color: #333333; font-size: 9px; font-family: Trebuchet MS, Verdana, Arial, Helvetica, sans-serif;"><span style="color: #333333; font-size: 9px; font-family: Trebuchet MS, Verdana, Arial, Helvetica, sans-serif;">&copy; Valve Corporation. All rights reserved. All trademarks are property of their respective owners in the US and other countries.</span></span></td>
    </tr>
  </table>
  <span style="color: #333333; font-size: 9px; font-family: Trebuchet MS, Verdana, Arial, Helvetica, sans-serif;"><br>
  </span>
</div>
  </body>
</html>


--------------060908020109090601040503--


